### ISSUE TITLE
Device control: serial

### ISSUE THREAD

**Issue by geonnave** [caninos-loucos/caninos-sdk#15]

**Comment by geonnave** [comment]
Inicialmente, eu estava pensando em uma API assim:

```python
import caninos_sdk as k9

labrador = k9.Labrador()

labrador.serial_usb.open(baudrate=9600, alias="arduino_uart") # default port /dev/ttyUSB0, overridable
# labrador.serial_header.enable(baudrate=9600, alias="arduino_uart") # default port /dev/ttyS0

labrador.arduino_uart.write(b"dados importantes")
respostas = labrador.arduino_uart.read()
labrador.arduino_uart.close()
```

Porém, a biblioteca pyserial é muito boa, acho que fazer um wrapper nela seria desnecessário. O que eu faria é simplesmente definir constantes com nomes intuitivos para as portas seriais da labrador, e usar a pyserial mesmo.

Assim, ao invés de

```python
import serial
ser = serial.Serial("/dev/ttyUSB0")
ser.write(b'dados enviados via serial')
ser.close()
```

teríamos

```python
import caninos_sdk as k9
import serial

ser = serial.Serial(k9.SERIAL_USB)

ser.write(b'dados enviados via serial')
ser.close()
```

**Comment by geonnave** [comment]
Na verdade, acabei mudando, meio que misturei as duas soluções: implementei o `__getattr__` na caninos_sdk.Serial, que joga os métodos `write`, `read` etc. para o pyserial. 

A solução está no PR #16.

**Comment by rodrigocebrian** [comment]
Acabei criando um breve código para o Arduino.


/*
  echo 
  reenvia para o computador o dado recebido pela serial
*/
 
byte byteRead;
 
void setup() {                
//configura a comunicação seria com baud rate de 9600
  Serial.begin(9600);
}
 
void loop() {
   
  if (Serial.available())  //verifica se tem dados diponível para leitura
  {
    byteRead = Serial.read(); //le bytwe mais recente no buffer da serial
    Serial.write(byteRead);   //reenvia para o computador o dado recebido
  }
}

**Comment by geonnave** [comment]
PR aberto para essa feature: https://github.com/caninos-loucos/caninos-sdk/pull/16
